namespace SourceFileVizualizer.Model
{
    public enum ECSVFile
    {
        non_empty_lines = 0,
        average_line_length = 1,
        line_length_deviation = 2,
        words = 3,
        unique_words = 4,
        chars = 5,
        tabulators = 6,
        spaces = 7,
        tab_indents = 8,
        space_indents = 9,
        whitespace_to_character_ratio = 10,
        comments = 11,
        comment_readability = 12,
        one_line_to_all_comments = 13,
        multi_line_to_all_comments = 14,
        inline_to_all_comments = 15,
        using_stl_libraries = 16,
        all_keywords = 17,
        if_keywords = 18,
        else_keywords = 19,
        for_keywords = 20,
        while_keywords = 21,
        switch_keywords = 22,
        do_keywords = 23,
        functions = 24,
        function_name_readability = 25,
        function_average_length = 26,
        function_length_deviation = 27,
        function_block_braces = 28,
        nesting_depth = 29,
        average_parameter_count = 30,
        parameter_count_deviation = 31,
        commands = 32,
        average_commands_per_line = 33,
        ternary_operations = 34,
        negation_operator = 35,
        uses_united_declarations = 36,
        uses_range_based_for = 37,
        author = 38,
    }
}
